const COLOR_ELABORACION = '#00FFFF'
const COLOR_REVISOR = '#0000FF'
const COLOR_DEFENSA_INTERNA = '#FF087F'
const COLOR_DIFERIDA = '#FFB60E'
const COLOR_DEFENSA_EXTERNA = '#FFFF00'
const COLOR_OBSERVADO = '#FF0000'
const COLOR_GRADUADO = '#00FF00'

module.exports = {
    COLOR_ELABORACION,
    COLOR_REVISOR,
    COLOR_DEFENSA_INTERNA,
    COLOR_DIFERIDA,
    COLOR_DEFENSA_EXTERNA,
    COLOR_OBSERVADO,
    COLOR_GRADUADO
}